dataeye:
  app-id: DATAEYE1
  config:
    java-timestamp-format: yyyy-MM-dd HH:mm:ss
    java-date-format: yyyy-MM-dd HH:mm:ss
    db-timestamp-format: YYYY-MM-DD HH24:MI:SS
    db-date-format: YYYY-MM-DD HH24:MI:SS
    login-logging-enable: true
    logout-logging-enable: false
    menu-access-logging-enable: true
    object-access-logging-enable: true
    object-access-logging-target-objects: 010201L, 010205L
    xss-filter-enable: false
    dummy-flag: false
  
  meta-config:
    atr-sqlsbst-inmemory-enable: false  #속성 쿼리 실행 결과 메모리 로딩 여부
    logical-delete-enable: false  #메타 삭제시 논리삭제 여부
    split-delimiter-char: \u00B6  #구분자로 사용할 char
    split-delimiter-string: \u00B6  #구분자로 사용할 string
    obj-rel-search-limit: 1000
  
  jqgrid:
    paging-enable: true
    scroll: false
    row-num: 20
    default-height: 500
    nav-edit-enable: true
    nav-add-enable: true
    nav-del-enable: true
    nav-search-enable: true
    nav-refresh-enable: true
    nav-view-enable: true
    top-pager: false 
    
  attach-file:
    upload-temp-path: /data/app/dataeye/file_attach/files_temp
    upload-read-path: /data/app/dataeye/file_attach/files_mgrd
    template-path: /data/app/dataeye/file_attach/template
  
  template:
    std-word-upload-template: 단어_일괄등록_템플릿.xlsx
    std-term-upload-template: 용어_일괄등록_템플릿.xlsx
    std-domain-upload-template: 도메인_일괄등록_템플릿.xlsx
    dsgn-tab-upload-template: 테이블목록_템플릿.xlsx
    dsgn-col-upload-template: 테이블정의서_템플릿.xlsx
    
  biz-std:
    word-nm-dupl-chk-enable: false
    word-abbr-auto-upper-enable: true
    term-abbr-length-chk-enable: true
    term-abbr-max-length: 30    
        
  mgr-role:    
    admin-role: ROLE_ADMIN            #어드민 롤
    admin-role-group: ADMIN_MENU_A    #어드민 롤 그룹
    system-role: ROLE_SYSTEM          #시스템 롤
    system-role-group: SYSTEM_MENU_A  #시스템 롤 그룹