CREATE TABLE PEN_UI_M
(
    UI_ID                VARCHAR2(100) NOT NULL ,
    DEL_YN               CHAR(1 BYTE) NOT NULL ,
    CRET_DT              TIMESTAMP(6) NOT NULL ,
    CRETR_ID             VARCHAR2(100) NOT NULL ,
    CHG_DT               TIMESTAMP(6) NOT NULL ,
    CHGR_ID              VARCHAR2(100) NOT NULL ,
    UI_NM                VARCHAR2(100) NULL ,
    USE_TYPE_CD          VARCHAR2(10) NULL ,
    UI_MODE_CD           VARCHAR2(10) NULL ,
    UI_TYPE_CD           VARCHAR2(20) NULL ,
    PGM_ID               VARCHAR2(100) NULL ,
    CONF_SBST         	 CLOB NULL
);

COMMENT ON TABLE PEN_UI_M IS '화면정의마스터';
COMMENT ON COLUMN PEN_UI_M.UI_ID IS '화면ID';
COMMENT ON COLUMN PEN_UI_M.DEL_YN IS '삭제여부';
COMMENT ON COLUMN PEN_UI_M.CRET_DT IS '생성일시';
COMMENT ON COLUMN PEN_UI_M.CRETR_ID IS '생성자';
COMMENT ON COLUMN PEN_UI_M.CHG_DT IS '수정일시';
COMMENT ON COLUMN PEN_UI_M.CHGR_ID IS '수정자';
COMMENT ON COLUMN PEN_UI_M.UI_NM IS '화면명';
COMMENT ON COLUMN PEN_UI_M.USE_TYPE_CD IS 'UI활용유형(WD:윈도우, LY:레이어)';
COMMENT ON COLUMN PEN_UI_M.UI_MODE_CD IS 'UI 모드(R:조회용, U:수정용)';
COMMENT ON COLUMN PEN_UI_M.UI_TYPE_CD IS 'UI 템플릿 유형코드(SIMPLE_UI, SHUTTLE_LR_UI, CUST_UI)';
COMMENT ON COLUMN PEN_UI_M.PGM_ID IS '프로그램아이디';
COMMENT ON COLUMN PEN_UI_M.CONF_SBST IS '프로그램 환경값(쿼리, 기타등등...)';

CREATE UNIQUE INDEX PK_PEN_UI_M ON PEN_UI_M
(UI_ID   ASC);



ALTER TABLE PEN_UI_M
    ADD CONSTRAINT  PK_PEN_UI_M PRIMARY KEY (UI_ID);



CREATE TABLE PEN_OBJ_TYPE_UI_D
(
	OBJ_TYPE_ID          VARCHAR2(100) NOT NULL ,
	UI_ID_SEQ            VARCHAR2(100) NOT NULL ,
	DEL_YN               CHAR(1 BYTE) NOT NULL ,
	CRET_DT              TIMESTAMP(6) NOT NULL ,
	CRETR_ID             VARCHAR2(100) NOT NULL ,
	CHG_DT               TIMESTAMP(6) NOT NULL ,
	CHGR_ID              VARCHAR2(100) NOT NULL ,
	UI_ID                VARCHAR2(100) NOT NULL ,
	UI_ALIAS_NM          VARCHAR2(100) NULL ,
	SORT_NO              NUMBER(10) NULL ,
	USE_YN               CHAR(1 BYTE) NULL 
);



CREATE UNIQUE INDEX PK_PEN_OBJ_TYPE_UI_D ON PEN_OBJ_TYPE_UI_D
(OBJ_TYPE_ID   ASC,UI_ID_SEQ   ASC);



ALTER TABLE PEN_OBJ_TYPE_UI_D
	ADD CONSTRAINT  PK_PEN_OBJ_TYPE_UI_D PRIMARY KEY (OBJ_TYPE_ID,UI_ID_SEQ);



----------------------------------------------------------------------------------------------------------------------------
 
CREATE TABLE PEN_APRV_M
(
	APRV_ID              VARCHAR2(300) NOT NULL ,
	DEL_YN               CHAR(1 BYTE) NOT NULL ,
	CRET_DT              TIMESTAMP(6) NOT NULL ,
	CRETR_ID             VARCHAR2(100) NOT NULL ,
	CHG_DT               TIMESTAMP(6) NOT NULL ,
	CHGR_ID              VARCHAR2(100) NOT NULL ,
	APRV_NM              VARCHAR2(300) NULL ,
	APRV_DESC            VARCHAR2(300) NULL ,
	APRV_TYPE_CD         VARCHAR2(10) NULL ,
	APRV_REQR_ID         VARCHAR2(100) NULL ,
	APRV_REQ_DT          TIMESTAMP(6) NULL ,
	LAST_LINE_ID         VARCHAR2(100) NULL ,
	LAST_STUS_CD         VARCHAR2(10) NULL ,
	APRV_OBJ_ID          VARCHAR2(300) NULL ,
	APRV_LINK_ID         VARCHAR2(300) NULL 
);

CREATE UNIQUE INDEX PK_PEN_APRV_M ON PEN_APRV_M
(APRV_ID   ASC);



ALTER TABLE PEN_APRV_M
	ADD CONSTRAINT  PK_PEN_APRV_M PRIMARY KEY (APRV_ID);


CREATE TABLE PEN_APRV_D
(
	APRV_ID              VARCHAR2(300) NOT NULL ,
	APRV_DETL_ID         VARCHAR2(300) NOT NULL ,
	DEL_YN               CHAR(1 BYTE) NOT NULL ,
	CRET_DT              TIMESTAMP(6) NOT NULL ,
	CRETR_ID             VARCHAR2(100) NOT NULL ,
	CHG_DT               TIMESTAMP(6) NOT NULL ,
	CHGR_ID              VARCHAR2(100) NOT NULL ,
	APRV_LINE_ID         VARCHAR2(100) NULL ,
	APRV_PRCS_SORT_NO    NUMBER(10) NULL ,
	APRV_PRCS_NM         VARCHAR2(300) NULL ,
	APRV_USER_ID         VARCHAR2(100) NULL ,
	APRV_DESC            VARCHAR2(300) NULL ,
	REAL_APRV_USER_ID    VARCHAR2(100) NULL ,
	APRV_DT              TIMESTAMP(6) NULL ,
	APRV_RSLT_CD         VARCHAR2(10) NULL ,
	APRV_LINE_OBJ_ID     VARCHAR2(300) NULL ,
	APRV_ATR01_VAL       VARCHAR2(300) NULL ,
	APRV_ATR02_VAL       VARCHAR2(300) NULL ,
	APRV_ATR03_VAL       VARCHAR2(300) NULL ,
	APRV_ATR04_VAL       VARCHAR2(300) NULL ,
	APRV_ATR05_VAL       VARCHAR2(300) NULL ,
	APRV_ATR06_VAL       VARCHAR2(300) NULL ,
	APRV_ATR07_VAL       VARCHAR2(300) NULL ,
	APRV_ATR08_VAL       VARCHAR2(300) NULL ,
	APRV_ATR09_VAL       VARCHAR2(300) NULL ,
	APRV_ATR10_VAL       VARCHAR2(300) NULL 
);



CREATE UNIQUE INDEX PK_PEN_APRV_D ON PEN_APRV_D
(APRV_ID   ASC,APRV_DETL_ID   ASC);



ALTER TABLE PEN_APRV_D
	ADD CONSTRAINT  PK_PEN_APRV_D PRIMARY KEY (APRV_ID,APRV_DETL_ID);






----------------------------------------------------------------------------------------

CREATE TABLE PEN_OBJ_D_T
(
	OBJ_TYPE_ID          VARCHAR2(100) NOT NULL ,
	OBJ_ID               VARCHAR2(300) NOT NULL ,
	ATR_ID_SEQ           NUMBER NOT NULL ,
	ATR_VAL_SEQ          NUMBER NOT NULL ,
	APRV_ID              VARCHAR2(300) NOT NULL ,
	DEL_YN               CHAR(1 BYTE) NOT NULL ,
	CRET_DT              TIMESTAMP(6) NOT NULL ,
	CRETR_ID             VARCHAR2(100) NOT NULL ,
	CHG_DT               TIMESTAMP(6) NOT NULL ,
	CHGR_ID              VARCHAR2(100) NOT NULL ,
	OBJ_ATR_VAL          VARCHAR2(4000) NULL 
);



CREATE UNIQUE INDEX PK_PEN_OBJ_D_T ON PEN_OBJ_D_T
(OBJ_TYPE_ID   ASC,OBJ_ID   ASC,ATR_ID_SEQ   ASC,ATR_VAL_SEQ   ASC, APRV_ID ASC);



ALTER TABLE PEN_OBJ_D_T
	ADD  PRIMARY KEY (OBJ_TYPE_ID,OBJ_ID,ATR_ID_SEQ,ATR_VAL_SEQ,APRV_ID);



CREATE  INDEX IX_PEN_OBJ_D_T_01 ON PEN_OBJ_D_T
(OBJ_TYPE_ID   ASC,OBJ_ID   ASC);



CREATE TABLE PEN_OBJ_M_T
(
	OBJ_TYPE_ID          VARCHAR2(100) NOT NULL ,
	OBJ_ID               VARCHAR2(300) NOT NULL ,
	APRV_ID              VARCHAR2(300) NOT NULL ,
	DEL_YN               CHAR(1 BYTE) NOT NULL ,
	CRET_DT              TIMESTAMP(6) NOT NULL ,
	CRETR_ID             VARCHAR2(100) NOT NULL ,
	CHG_DT               TIMESTAMP(6) NOT NULL ,
	CHGR_ID              VARCHAR2(100) NOT NULL ,
	OBJ_NM               VARCHAR2(300) NULL ,
	OBJ_ABBR_NM          VARCHAR2(300) NULL ,
	OBJ_DESC             VARCHAR2(1000) NULL ,
	PATH_OBJ_TYPE_ID     VARCHAR2(100) NULL ,
	PATH_OBJ_ID          VARCHAR2(300) NULL 
);



CREATE UNIQUE INDEX PK_PEN_OBJ_M_T ON PEN_OBJ_M_T
(OBJ_TYPE_ID   ASC,OBJ_ID   ASC, APRV_ID ASC);



ALTER TABLE PEN_OBJ_M_T
	ADD  PRIMARY KEY (OBJ_TYPE_ID,OBJ_ID,APRV_ID);



CREATE  INDEX IX_PEN_OBJ_M_T_01 ON PEN_OBJ_M_T
(PATH_OBJ_TYPE_ID   ASC,PATH_OBJ_ID   ASC, APRV_ID ASC);



CREATE TABLE PEN_OBJ_R_T
(
	OBJ_TYPE_ID          VARCHAR2(100) NOT NULL ,
	OBJ_ID               VARCHAR2(300) NOT NULL ,
	REL_OBJ_TYPE_ID      VARCHAR2(100) NOT NULL ,
	REL_OBJ_ID           VARCHAR2(300) NOT NULL ,
	APRV_ID              VARCHAR2(300) NOT NULL ,
	DEL_YN               CHAR(1 BYTE) NOT NULL ,
	CRET_DT              TIMESTAMP(6) NOT NULL ,
	CRETR_ID             VARCHAR2(100) NOT NULL ,
	CHG_DT               TIMESTAMP(6) NOT NULL ,
	CHGR_ID              VARCHAR2(100) NOT NULL ,
	REL_TYPE_ID          VARCHAR2(100) NULL ,
	OBJ_REL_ANALS_CD     VARCHAR2(10) NULL 
);



CREATE UNIQUE INDEX PK_PEN_OBJ_R_T ON PEN_OBJ_R_T
(OBJ_TYPE_ID   ASC,OBJ_ID   ASC,REL_OBJ_TYPE_ID   ASC,REL_OBJ_ID   ASC, APRV_ID ASC);



ALTER TABLE PEN_OBJ_R_T
	ADD  PRIMARY KEY (OBJ_TYPE_ID,OBJ_ID,REL_OBJ_TYPE_ID,REL_OBJ_ID, APRV_ID);




-------------------------------------------------------------------------

CREATE TABLE PEN_OBJ_CMMT_D
(
	OBJ_TYPE_ID          VARCHAR2(100) NOT NULL ,
	OBJ_ID               VARCHAR2(300) NOT NULL ,
	CMMT_ID              VARCHAR2(300) NOT NULL ,
	DEL_YN               CHAR(1 BYTE) NOT NULL ,
	CRET_DT              TIMESTAMP(6) NOT NULL ,
	CRETR_ID             VARCHAR2(100) NOT NULL ,
	CHG_DT               TIMESTAMP(6) NOT NULL ,
	CHGR_ID              VARCHAR2(100) NOT NULL ,
	CMMT_DESC            VARCHAR2(4000) NULL 
);



CREATE UNIQUE INDEX XPKPEN_OBJ_CMMT_D ON PEN_OBJ_CMMT_D
(OBJ_TYPE_ID   ASC,OBJ_ID   ASC,CMMT_ID   ASC);



ALTER TABLE PEN_OBJ_CMMT_D
	ADD  PRIMARY KEY (OBJ_TYPE_ID,OBJ_ID,CMMT_ID);



CREATE TABLE PEN_OBJ_REQ_D
(
	OBJ_TYPE_ID          VARCHAR2(100) NOT NULL ,
	OBJ_ID               VARCHAR2(300) NOT NULL ,
	REQ_ID               VARCHAR2(300) NOT NULL ,
	STUS_ID              VARCHAR2(300) NOT NULL ,
	DEL_YN               CHAR(1 BYTE) NOT NULL ,
	CRET_DT              TIMESTAMP(6) NOT NULL ,
	CRETR_ID             VARCHAR2(100) NOT NULL ,
	CHG_DT               TIMESTAMP(6) NOT NULL ,
	CHGR_ID              VARCHAR2(100) NOT NULL ,
	STUS_CD              VARCHAR2(10) NULL ,
	STUS_USER_ID         VARCHAR2(100) NULL ,
	STUS_DESC            VARCHAR2(4000) NULL ,
	STUS_DT              TIMESTAMP(6) NULL ,
	STUS_LINK_ID         VARCHAR2(300) NULL 
);



CREATE UNIQUE INDEX XPKPEN_OBJ_REQ_D ON PEN_OBJ_REQ_D
(OBJ_TYPE_ID   ASC,OBJ_ID   ASC,REQ_ID   ASC,STUS_ID   ASC);



ALTER TABLE PEN_OBJ_REQ_D
	ADD  PRIMARY KEY (OBJ_TYPE_ID,OBJ_ID,REQ_ID,STUS_ID);



CREATE TABLE PEN_OBJ_TAG_D
(
	OBJ_TYPE_ID          VARCHAR2(100) NOT NULL ,
	OBJ_ID               VARCHAR2(300) NOT NULL ,
	OBJ_TAG_NM           VARCHAR2(300) NOT NULL ,
	DEL_YN               CHAR(1 BYTE) NOT NULL ,
	CRET_DT              TIMESTAMP(6) NOT NULL ,
	CRETR_ID             VARCHAR2(100) NOT NULL ,
	CHG_DT               TIMESTAMP(6) NOT NULL ,
	CHGR_ID              VARCHAR2(100) NOT NULL 
);



CREATE UNIQUE INDEX XPKPEN_OBJ_TAG_D ON PEN_OBJ_TAG_D
(OBJ_TYPE_ID   ASC,OBJ_ID   ASC,OBJ_TAG_NM   ASC);



ALTER TABLE PEN_OBJ_TAG_D
	ADD  PRIMARY KEY (OBJ_TYPE_ID,OBJ_ID,OBJ_TAG_NM);


