/*
 * 객체마스터 이력
 */
CREATE TABLE PEN_OBJ_M_H
(
  OBJ_TYPE_ID       VARCHAR2(100)          NOT NULL,
  OBJ_ID            VARCHAR2(300)          NOT NULL,
  HST_SEQ        VARCHAR2(300)          NOT NULL,
  HST_CRET_DT           TIMESTAMP(6)                NOT NULL,
  HST_CRETR_ID          VARCHAR2(100)          NOT NULL,
  REQ_SEQ        VARCHAR2(300)          NULL,
  DEL_YN            CHAR(1)                NOT NULL,
  CRET_DT           TIMESTAMP(6)                NOT NULL,
  CRETR_ID          VARCHAR2(100)          NOT NULL,
  CHG_DT            TIMESTAMP(6)                NOT NULL,
  CHGR_ID           VARCHAR2(100)          NOT NULL,
  ADM_OBJ_ID        VARCHAR2(300),
  OBJ_NM            VARCHAR2(300),
  OBJ_ABBR_NM       VARCHAR2(300),
  OBJ_DESC          VARCHAR2(2000),
  PATH_OBJ_TYPE_ID  VARCHAR2(100),
  PATH_OBJ_ID       VARCHAR2(300)
);

COMMENT ON TABLE PEN_OBJ_M_H IS '객체마스터';
COMMENT ON COLUMN PEN_OBJ_M_H.OBJ_TYPE_ID IS '객체유형아이디';
COMMENT ON COLUMN PEN_OBJ_M_H.OBJ_ID IS '객체아이디';
COMMENT ON COLUMN PEN_OBJ_M_H.HST_SEQ IS '이력 일련번호';
COMMENT ON COLUMN PEN_OBJ_M_H.HST_CRET_DT IS '이력 생성일시';
COMMENT ON COLUMN PEN_OBJ_M_H.HST_CRETR_ID IS '이력 생성자';
COMMENT ON COLUMN PEN_OBJ_M_H.REQ_SEQ IS '요청 일련번호';
COMMENT ON COLUMN PEN_OBJ_M_H.DEL_YN IS '삭제여부';
COMMENT ON COLUMN PEN_OBJ_M_H.CRET_DT IS '생성일시';
COMMENT ON COLUMN PEN_OBJ_M_H.CRETR_ID IS '생성자';
COMMENT ON COLUMN PEN_OBJ_M_H.CHG_DT IS '수정일시';
COMMENT ON COLUMN PEN_OBJ_M_H.CHGR_ID IS '수정자';
COMMENT ON COLUMN PEN_OBJ_M_H.ADM_OBJ_ID IS '관리객체아이디';
COMMENT ON COLUMN PEN_OBJ_M_H.OBJ_NM IS '객체명';
COMMENT ON COLUMN PEN_OBJ_M_H.OBJ_ABBR_NM IS '객체약어명';
COMMENT ON COLUMN PEN_OBJ_M_H.OBJ_DESC IS '객체설명';
COMMENT ON COLUMN PEN_OBJ_M_H.PATH_OBJ_TYPE_ID IS '경로객체유형아이디';
COMMENT ON COLUMN PEN_OBJ_M_H.PATH_OBJ_ID IS '경로객체아이디';

CREATE UNIQUE INDEX PK_PEN_OBJ_M_H ON PEN_OBJ_M_H
(OBJ_TYPE_ID, OBJ_ID, HST_SEQ);


ALTER TABLE PEN_OBJ_M_H ADD (
  PRIMARY KEY
  (OBJ_TYPE_ID, OBJ_ID, HST_SEQ)
  USING INDEX PK_PEN_OBJ_M_H);
  
/*
 * 객체상세 이력
 */  
CREATE TABLE PEN_OBJ_D_H
(
  OBJ_TYPE_ID  VARCHAR2(100)               NOT NULL,
  OBJ_ID       VARCHAR2(300)               NOT NULL,
  ATR_ID_SEQ   NUMBER                           NOT NULL,
  ATR_VAL_SEQ  NUMBER                           NOT NULL,
  HST_SEQ        VARCHAR2(300)          NOT NULL,
  HST_CRET_DT           TIMESTAMP(6)                NOT NULL,
  HST_CRETR_ID          VARCHAR2(100)          NOT NULL,
  REQ_SEQ        VARCHAR2(300)          NULL,
  DEL_YN       CHAR(1)                     NOT NULL,
  CRET_DT      TIMESTAMP(6)                     NOT NULL,
  CRETR_ID     VARCHAR2(100)               NOT NULL,
  CHG_DT       TIMESTAMP(6)                     NOT NULL,
  CHGR_ID      VARCHAR2(100)               NOT NULL,
  OBJ_ATR_VAL  VARCHAR2(4000)
);

COMMENT ON TABLE PEN_OBJ_D_H IS '객체속성';
COMMENT ON COLUMN PEN_OBJ_D_H.OBJ_TYPE_ID IS '객체유형아이디';
COMMENT ON COLUMN PEN_OBJ_D_H.OBJ_ID IS '객체아이디';
COMMENT ON COLUMN PEN_OBJ_D_H.ATR_ID_SEQ IS '객체속성순번';
COMMENT ON COLUMN PEN_OBJ_D_H.ATR_VAL_SEQ IS '객체값순번';
COMMENT ON COLUMN PEN_OBJ_D_H.HST_SEQ IS '이력 일련번호';
COMMENT ON COLUMN PEN_OBJ_D_H.HST_CRET_DT IS '이력 생성일시';
COMMENT ON COLUMN PEN_OBJ_D_H.HST_CRETR_ID IS '이력 생성자';
COMMENT ON COLUMN PEN_OBJ_D_H.REQ_SEQ IS '요청 일련번호';
COMMENT ON COLUMN PEN_OBJ_D_H.DEL_YN IS '삭제여부';
COMMENT ON COLUMN PEN_OBJ_D_H.CRET_DT IS '생성일시';
COMMENT ON COLUMN PEN_OBJ_D_H.CRETR_ID IS '생성자';
COMMENT ON COLUMN PEN_OBJ_D_H.CHG_DT IS '수정일시';
COMMENT ON COLUMN PEN_OBJ_D_H.CHGR_ID IS '수정자';
COMMENT ON COLUMN PEN_OBJ_D_H.OBJ_ATR_VAL IS '객체속성값';



CREATE UNIQUE INDEX PK_PEN_OBJ_D_H ON PEN_OBJ_D_H
(OBJ_TYPE_ID, OBJ_ID, ATR_ID_SEQ, ATR_VAL_SEQ, HST_SEQ);


ALTER TABLE PEN_OBJ_D_H ADD (
  PRIMARY KEY
  (OBJ_TYPE_ID, OBJ_ID, ATR_ID_SEQ, ATR_VAL_SEQ, HST_SEQ)
  USING INDEX PK_PEN_OBJ_D_H);

/*
 * 객체관계 이력
 */    
CREATE TABLE PEN_OBJ_R_H
(
  OBJ_TYPE_ID       VARCHAR2(100)          NOT NULL,
  OBJ_ID            VARCHAR2(300)          NOT NULL,
  REL_OBJ_TYPE_ID   VARCHAR2(100)          NOT NULL,
  REL_OBJ_ID        VARCHAR2(300)          NOT NULL,
  HST_SEQ        VARCHAR2(300)          NOT NULL,
  HST_CRET_DT           TIMESTAMP(6)                NOT NULL,
  HST_CRETR_ID          VARCHAR2(100)          NOT NULL,
  REQ_SEQ        VARCHAR2(300)          NULL,
  DEL_YN            CHAR(1)                NOT NULL,
  CRET_DT           TIMESTAMP(6)                NOT NULL,
  CRETR_ID          VARCHAR2(100)          NOT NULL,
  CHG_DT            TIMESTAMP(6)                NOT NULL,
  CHGR_ID           VARCHAR2(100)          NOT NULL,
  REL_TYPE_ID       VARCHAR2(100),
  OBJ_REL_ANALS_CD  VARCHAR2(3)
);

COMMENT ON TABLE PEN_OBJ_R_H IS '객체관계';

CREATE UNIQUE INDEX PK_PEN_OBJ_R_H ON PEN_OBJ_R_H
(OBJ_TYPE_ID, OBJ_ID, REL_OBJ_TYPE_ID, REL_OBJ_ID,HST_SEQ);


ALTER TABLE PEN_OBJ_R_H ADD (
  PRIMARY KEY
  (OBJ_TYPE_ID, OBJ_ID, REL_OBJ_TYPE_ID, REL_OBJ_ID, HST_SEQ)
  USING INDEX PK_PEN_OBJ_R_H);
