CREATE TABLE PEN_COLT_DB_L
(
    LOG_ID              NVARCHAR(300) NOT NULL,
    LOG_DT              TIMESTAMP NOT NULL,
    BATCH_ID            NVARCHAR(300) NOT NULL,
    DB_ID               NVARCHAR(300) NOT NULL,
    LOG_TYPE            NVARCHAR(10) NOT NULL,
    OBJ_TYPE            NVARCHAR(20) NOT NULL,
    OBJ_TYPE_ID         NVARCHAR(100) NOT NULL,
    OBJ_ID              NVARCHAR(300) NOT NULL,
    OBJ_NM              NVARCHAR(300),
    PATH_OBJ_TYPE_ID    NVARCHAR(100),
    PATH_OBJ_ID         NVARCHAR(100),
    LOG_TEXT            NVARCHAR(10000)
)
DISTRIBUTE ON ( LOG_ID, LOG_DT, BATCH_ID, DB_ID );

CREATE TABLE PEN_COLT_TAB_T
(
    BATCH_ID        NVARCHAR(300),
    DB_ID           NVARCHAR(300),
    DB_NM           NVARCHAR(300),
    SCHEMA_NM       NVARCHAR(300),
    OWNER_NM        NVARCHAR(100),
    TABLE_NM        NVARCHAR(300),
    TABLE_CMNT      NVARCHAR(500),
    TABLE_CRET_DT   NVARCHAR(14),
    TABLE_CHG_DT    NVARCHAR(14),
    TAB_OBJ_ID      NVARCHAR(300)
)
DISTRIBUTE ON ( BATCH_ID, DB_ID, TABLE_NM );

CREATE TABLE PEN_COLT_TAB_COL_T
(
    BATCH_ID        NVARCHAR(300),
    DB_ID           NVARCHAR(300),
    DB_NM           NVARCHAR(300),
    SCHEMA_NM       NVARCHAR(300),
    OWNER_NM        NVARCHAR(100),
    TABLE_NM        NVARCHAR(300),
    COLUMN_NM       NVARCHAR(300),
    COLUMN_CMNT     NVARCHAR(500),
    COLUMN_ORD      NVARCHAR(5),
    DATA_TYPE       NVARCHAR(100),
    DATA_LEN        NVARCHAR(100),
    DATA_SCALE      NVARCHAR(100),
    NOT_NULL_YN     NCHAR(1),
    DEFAULT_VAL     NVARCHAR(100),
    PK_ORD          NVARCHAR(5),
    FK_YN           NCHAR(1),
    DISTRIB_KEY_ORD NVARCHAR(5),
    TAB_OBJ_ID      NVARCHAR(300),
    COL_OBJ_ID      NVARCHAR(300)
)
DISTRIBUTE ON ( BATCH_ID, DB_ID, TABLE_NM, COLUMN_NM );


CREATE TABLE PEN_COLT_VIEW_T
(
    BATCH_ID        NVARCHAR(300),
    DB_ID           NVARCHAR(300),
    DB_NM           NVARCHAR(300),
    SCHEMA_NM       NVARCHAR(300),
    OWNER_NM        NVARCHAR(100),
    VIEW_NM         NVARCHAR(300),
    VIEW_CMNT       NVARCHAR(500),
    VIEW_CRET_DT    NVARCHAR(14),
    VIEW_CHG_DT     NVARCHAR(14),
    VIEW_OBJ_ID     NVARCHAR(300)
)
DISTRIBUTE ON ( BATCH_ID, DB_ID, VIEW_NM);

CREATE TABLE PEN_COLT_VIEW_COL_T
(
    BATCH_ID    NVARCHAR(300),
    DB_ID       NVARCHAR(300),
    DB_NM       NVARCHAR(300),
    SCHEMA_NM   NVARCHAR(300),
    OWNER_NM    NVARCHAR(100),
    VIEW_NM     NVARCHAR(300),
    COLUMN_NM   NVARCHAR(300),
    COLUMN_CMNT NVARCHAR(500),
    COLUMN_ORD  NVARCHAR(5),
    DATA_TYPE   NVARCHAR(100),
    DATA_LEN    NVARCHAR(100),
    DATA_SCALE  NVARCHAR(100),
    NOT_NULL_YN NCHAR(1),
    VIEW_OBJ_ID NVARCHAR(300),
    COL_OBJ_ID  NVARCHAR(300)
)
DISTRIBUTE ON ( BATCH_ID, DB_ID, VIEW_NM, COLUMN_NM);


CREATE TABLE PEN_COLT_PROC_T
(
    BATCH_ID        NVARCHAR(300),
    DB_ID           NVARCHAR(300),
    DB_NM           NVARCHAR(300),
    SCHEMA_NM       NVARCHAR(300),
    OWNER_NM        NVARCHAR(100),
    PROC_NM         NVARCHAR(300),
    PROC_CMNT       NVARCHAR(500),
    PROC_CRET_DT    NVARCHAR(14),
    PROC_CHG_DT     NVARCHAR(14),
    PROC_OBJ_ID     NVARCHAR(300)
)
DISTRIBUTE ON ( BATCH_ID, DB_ID, PROC_NM);
