/*
 * 어플리케이션 마스터
 */
CREATE TABLE PEN_APP_M
(
    APP_ID NVARCHAR2(200) NOT NULL,
    DEL_YN NCHAR(1) NOT NULL,
    CRET_DT TIMESTAMP NOT NULL,
    CRETR_ID NVARCHAR2(200) NOT NULL,
    CHG_DT TIMESTAMP NOT NULL,
    CHGR_ID NVARCHAR2(200) NOT NULL,
    APP_NM NVARCHAR2(200) NOT NULL,
    APP_DESC NVARCHAR2(2000) ,
    USE_YN NCHAR(1) NOT NULL
);

ALTER TABLE PEN_APP_M ADD CONSTRAINT 
PK_APP_M PRIMARY KEY 
(APP_ID); 

COMMENT ON TABLE PEN_APP_M IS '어플리케이션 마스터';

COMMENT ON COLUMN PEN_APP_M.APP_ID IS '어플리케이션 ID';
COMMENT ON COLUMN PEN_APP_M.DEL_YN IS '삭제여부';
COMMENT ON COLUMN PEN_APP_M.CRET_DT IS '생성일시';
COMMENT ON COLUMN PEN_APP_M.CRETR_ID IS '생성자';
COMMENT ON COLUMN PEN_APP_M.CHG_DT IS '수정일시';
COMMENT ON COLUMN PEN_APP_M.CHGR_ID IS '수정자';
COMMENT ON COLUMN PEN_APP_M.APP_NM IS '어플리케이션 명';
COMMENT ON COLUMN PEN_APP_M.APP_DESC IS '어플리케이션 설명';
COMMENT ON COLUMN PEN_APP_M.USE_YN IS '사용여부';

INSERT INTO PEN_APP_M VALUES('DATAEYE', 'N', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin', '데이타아이', '데이타아이', 'Y');

/*
 * 프로그램 마스터
 */
CREATE TABLE PEN_PGM_M
(
    PGM_ID NVARCHAR2(200) NOT NULL,
    DEL_YN NCHAR(1) NOT NULL,
    CRET_DT TIMESTAMP NOT NULL,
    CRETR_ID NVARCHAR2(200) NOT NULL,
    CHG_DT TIMESTAMP NOT NULL,
    CHGR_ID NVARCHAR2(200) NOT NULL,
    PGM_NM NVARCHAR2(200) NOT NULL,
    PGM_DESC NVARCHAR2(2000) ,
    VIEW_ID NVARCHAR2(200) NOT NULL,
    APP_ID NVARCHAR2(200) NOT NULL,
    USE_YN NCHAR(1) NOT NULL
);

ALTER TABLE PEN_PGM_M ADD CONSTRAINT 
PK_PGM_M PRIMARY KEY 
(PGM_ID); 

COMMENT ON TABLE PEN_PGM_M IS '프로그램 마스터';

COMMENT ON COLUMN PEN_PGM_M.PGM_ID IS '프로그램ID';
COMMENT ON COLUMN PEN_PGM_M.DEL_YN IS '삭제여부';
COMMENT ON COLUMN PEN_PGM_M.CRET_DT IS '생성일시';
COMMENT ON COLUMN PEN_PGM_M.CRETR_ID IS '생성자';
COMMENT ON COLUMN PEN_PGM_M.CHG_DT IS '수정일시';
COMMENT ON COLUMN PEN_PGM_M.CHGR_ID IS '수정자';
COMMENT ON COLUMN PEN_PGM_M.PGM_NM IS '프로그램명';
COMMENT ON COLUMN PEN_PGM_M.PGM_DESC IS '프로그램 설명';
COMMENT ON COLUMN PEN_PGM_M.VIEW_ID IS '뷰 ID';
COMMENT ON COLUMN PEN_PGM_M.APP_ID IS '어플리케이션 ID';
COMMENT ON COLUMN PEN_PGM_M.USE_YN IS '사용여부';

/*
 * 메뉴 마스터
 */
CREATE TABLE PEN_MENU_M
(
    MENU_ID NVARCHAR2(200) NOT NULL,
    DEL_YN NCHAR(1) NOT NULL,
    CRET_DT TIMESTAMP NOT NULL,
    CRETR_ID NVARCHAR2(200) NOT NULL,
    CHG_DT TIMESTAMP NOT NULL,
    CHGR_ID NVARCHAR2(200) NOT NULL,
    MENU_ADM_ID NVARCHAR2(200) ,
    MENU_NM NVARCHAR2(200) NOT NULL,
    MENU_DESC NVARCHAR2(2000) ,
    ICON_CLASS NVARCHAR2(200) ,
    PGM_ID NVARCHAR2(200) ,
    UP_MENU_ID NVARCHAR2(200) ,
    MENU_TYPE NVARCHAR2(20) NOT NULL,
    APP_ID NVARCHAR2(200) NOT NULL,
    SORT_NO NUMBER NOT NULL,
    USE_YN NCHAR(1) NOT NULL
);

ALTER TABLE PEN_MENU_M ADD CONSTRAINT 
PK_MENU_M PRIMARY KEY 
(MENU_ID); 

COMMENT ON TABLE PEN_MENU_M IS '메뉴 마스터';

COMMENT ON COLUMN PEN_MENU_M.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN PEN_MENU_M.DEL_YN IS '삭제여부';
COMMENT ON COLUMN PEN_MENU_M.CRET_DT IS '생성일시';
COMMENT ON COLUMN PEN_MENU_M.CRETR_ID IS '생성자';
COMMENT ON COLUMN PEN_MENU_M.CHG_DT IS '수정일시';
COMMENT ON COLUMN PEN_MENU_M.CHGR_ID IS '수정자';
COMMENT ON COLUMN PEN_MENU_M.MENU_ADM_ID IS '메뉴관리ID';
COMMENT ON COLUMN PEN_MENU_M.MENU_NM IS '메뉴명';
COMMENT ON COLUMN PEN_MENU_M.MENU_DESC IS '메뉴 설명';
COMMENT ON COLUMN PEN_MENU_M.ICON_CLASS IS '메뉴아이콘 CLASS';
COMMENT ON COLUMN PEN_MENU_M.PGM_ID IS '프로그램ID';
COMMENT ON COLUMN PEN_MENU_M.UP_MENU_ID IS '상위메뉴 ID';
COMMENT ON COLUMN PEN_MENU_M.MENU_TYPE IS '메뉴유형(FOLDER/PGM)';
COMMENT ON COLUMN PEN_MENU_M.APP_ID IS '어플리케이션 ID';
COMMENT ON COLUMN PEN_MENU_M.SORT_NO IS '정렬순서';
COMMENT ON COLUMN PEN_MENU_M.USE_YN IS '사용여부';

/*
 * ROLE 마스타
 */
CREATE TABLE PEN_ROLE_M
(
    ROLE_ID NVARCHAR2(200) NOT NULL,
    DEL_YN NCHAR(1) NOT NULL,
    CRET_DT TIMESTAMP NOT NULL,
    CRETR_ID NVARCHAR2(200) NOT NULL,
    CHG_DT TIMESTAMP NOT NULL,
    CHGR_ID NVARCHAR2(200) NOT NULL,
    ROLE_NM NVARCHAR2(200) NOT NULL,
    ROLE_DESC NVARCHAR2(2000) ,
    APP_ID NVARCHAR2(200) NOT NULL,
    USE_YN NCHAR(1) NOT NULL
);

ALTER TABLE PEN_ROLE_M ADD CONSTRAINT 
PK_ROLE_M PRIMARY KEY 
(ROLE_ID); 

COMMENT ON TABLE PEN_ROLE_M IS '롤 마스터';

COMMENT ON COLUMN PEN_ROLE_M.ROLE_ID IS '롤ID';
COMMENT ON COLUMN PEN_ROLE_M.DEL_YN IS '삭제여부';
COMMENT ON COLUMN PEN_ROLE_M.CRET_DT IS '생성일시';
COMMENT ON COLUMN PEN_ROLE_M.CRETR_ID IS '생성자';
COMMENT ON COLUMN PEN_ROLE_M.CHG_DT IS '수정일시';
COMMENT ON COLUMN PEN_ROLE_M.CHGR_ID IS '수정자';
COMMENT ON COLUMN PEN_ROLE_M.ROLE_NM IS '롤명';
COMMENT ON COLUMN PEN_ROLE_M.ROLE_DESC IS '롤 설명';
COMMENT ON COLUMN PEN_ROLE_M.APP_ID IS '어플리케이션 ID';
COMMENT ON COLUMN PEN_ROLE_M.USE_YN IS '사용여부';

/*
 * ROLE & 사용자 관계
 */
CREATE TABLE PEN_ROLE_USER_R
(
    ROLE_ID NVARCHAR2(200) NOT NULL,
    USER_ID NVARCHAR2(200) NOT NULL,
    DEL_YN NCHAR(1) NOT NULL,
    CRET_DT TIMESTAMP NOT NULL,
    CRETR_ID NVARCHAR2(200) NOT NULL,
    CHG_DT TIMESTAMP NOT NULL,
    CHGR_ID NVARCHAR2(200) NOT NULL
);

ALTER TABLE PEN_ROLE_USER_R ADD CONSTRAINT 
PK_ROLE_USER_R PRIMARY KEY 
(ROLE_ID, USER_ID); 

COMMENT ON TABLE PEN_ROLE_USER_R IS '롤 사용자 관계';

COMMENT ON COLUMN PEN_ROLE_USER_R.ROLE_ID IS '롤ID';
COMMENT ON COLUMN PEN_ROLE_USER_R.USER_ID IS '사용자ID';
COMMENT ON COLUMN PEN_ROLE_USER_R.DEL_YN IS '삭제여부';
COMMENT ON COLUMN PEN_ROLE_USER_R.CRET_DT IS '생성일시';
COMMENT ON COLUMN PEN_ROLE_USER_R.CRETR_ID IS '생성자';
COMMENT ON COLUMN PEN_ROLE_USER_R.CHG_DT IS '수정일시';
COMMENT ON COLUMN PEN_ROLE_USER_R.CHGR_ID IS '수정자';

/*
 * 롤 & 메뉴 관계
 */
CREATE TABLE PEN_ROLE_MENU_R
(
    ROLE_ID NVARCHAR2(200) NOT NULL,
    MENU_ID NVARCHAR2(200) NOT NULL,
    DEL_YN NCHAR(1) NOT NULL,
    CRET_DT TIMESTAMP NOT NULL,
    CRETR_ID NVARCHAR2(200) NOT NULL,
    CHG_DT TIMESTAMP NOT NULL,
    CHGR_ID NVARCHAR2(200) NOT NULL,
    C_AUTH NCHAR(1) NOT NULL,
    R_AUTH NCHAR(1) NOT NULL,
    U_AUTH NCHAR(1) NOT NULL,
    D_AUTH NCHAR(1) NOT NULL,
    E_AUTH NCHAR(1) NOT NULL
);

ALTER TABLE PEN_ROLE_MENU_R ADD CONSTRAINT 
PK_ROLE_MENU_R PRIMARY KEY 
(ROLE_ID, MENU_ID); 

COMMENT ON TABLE PEN_ROLE_MENU_R IS '롤 메뉴  관계';

COMMENT ON COLUMN PEN_ROLE_MENU_R.ROLE_ID IS '롤ID';
COMMENT ON COLUMN PEN_ROLE_MENU_R.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN PEN_ROLE_MENU_R.DEL_YN IS '삭제여부';
COMMENT ON COLUMN PEN_ROLE_MENU_R.CRET_DT IS '생성일시';
COMMENT ON COLUMN PEN_ROLE_MENU_R.CRETR_ID IS '생성자';
COMMENT ON COLUMN PEN_ROLE_MENU_R.CHG_DT IS '수정일시';
COMMENT ON COLUMN PEN_ROLE_MENU_R.CHGR_ID IS '수정자';
COMMENT ON COLUMN PEN_ROLE_MENU_R.C_AUTH IS '등록권한';
COMMENT ON COLUMN PEN_ROLE_MENU_R.R_AUTH IS '읽기권한';
COMMENT ON COLUMN PEN_ROLE_MENU_R.U_AUTH IS '수정권한';
COMMENT ON COLUMN PEN_ROLE_MENU_R.D_AUTH IS '삭제권한';
COMMENT ON COLUMN PEN_ROLE_MENU_R.E_AUTH IS '실행권한';
  
/*
 * 객체 유형 마스터
 */
CREATE TABLE PEN_OBJ_TYPE_M
(
  OBJ_TYPE_ID     VARCHAR2(100)            NOT NULL,
  DEL_YN          CHAR(1)                  NOT NULL,
  CRET_DT         TIMESTAMP(6)                  NOT NULL,
  CRETR_ID        VARCHAR2(100)            NOT NULL,
  CHG_DT          TIMESTAMP(6)                  NOT NULL,
  CHGR_ID         VARCHAR2(100)            NOT NULL,
  OBJ_TYPE_NM     VARCHAR2(100),
  OBJ_TYPE_DESC   VARCHAR2(1000),
  SORT_NO         NUMBER,
  UP_OBJ_TYPE_ID  VARCHAR2(100),
  HIER_LEV_NO     VARCHAR2(100),
  LST_LEV_YN      CHAR(1),
  ATR_ADM_CD      VARCHAR2(10),
  STLM_YN         CHAR(1),
  HST_YN          CHAR(1),
  TAG_YN          CHAR(1),
  CMMT_YN          CHAR(1)
);

COMMENT ON TABLE PEN_OBJ_TYPE_M IS '객체유형마스터';

CREATE UNIQUE INDEX PK_PEN_OBJ_TYPE_M ON PEN_OBJ_TYPE_M
(OBJ_TYPE_ID);


ALTER TABLE PEN_OBJ_TYPE_M ADD (
  PRIMARY KEY
  (OBJ_TYPE_ID)
  USING INDEX PK_PEN_OBJ_TYPE_M);  