CREATE TABLE PEN_SQL_POOL_M (
    SQL_ID VARCHAR2(100) NOT NULL,
    DEL_YN CHAR(1) NOT NULL,
    CRET_DT TIMESTAMP(6) NOT NULL,
    CRETR_ID VARCHAR2(100) NOT NULL,
    CHG_DT TIMESTAMP(6) NOT NULL,
    CHGR_ID VARCHAR2(100) NOT NULL,
    SQL_NM VARCHAR2(100) NOT NULL,
    SQL_TYPE_CD CHAR(1) NOT NULL,
    SQL_SBST VARCHAR2(4000) ,
    GRID_OPTS VARCHAR2(4000) ,
    SQL_SBST2 VARCHAR2(4000) ,
    GRID_OPTS2 VARCHAR2(4000),
    AUTH_CHK_YN CHAR(1),
    AUTH_CHK_SBST VARCHAR2(4000)
);

ALTER TABLE PEN_SQL_POOL_M ADD CONSTRAINT 
PK_PEN_SQL_POOL_M PRIMARY KEY 
(SQL_ID); 