/*
 * 요청 테이블
 */
CREATE TABLE PEN_OBJ_REQ_D
(
    OBJ_TYPE_ID VARCHAR2(100) NOT NULL,
    OBJ_ID  VARCHAR2(300) NOT NULL,
    REQ_ID VARCHAR2(300) NOT NULL,
    STUS_ID VARCHAR2(300) NOT NULL,
    DEL_YN CHAR(1) NOT NULL,
    CRET_DT TIMESTAMP(6) NOT NULL,
    CRETR_ID VARCHAR2(100) NOT NULL,
    CHG_DT TIMESTAMP(6) NOT NULL,
    CHGR_ID VARCHAR2(100) NOT NULL,
    STUS_CD VARCHAR2(10),
    STUS_USER_ID VARCHAR2(100),
    STUS_DESC VARCHAR2(4000),
    STUS_DT TIMESTAMP(6),
    STUS_LINK_ID VARCHAR2(300)
);

CREATE UNIQUE INDEX PK_PEN_OBJ_REQ_D 
ON PEN_OBJ_REQ_D (
    OBJ_TYPE_ID ASC,
    OBJ_ID  ASC,
    REQ_ID ASC,
    STUS_ID ASC
);

ALTER TABLE PEN_OBJ_REQ_D ADD (
  PRIMARY KEY
  (
    OBJ_TYPE_ID,
    OBJ_ID,
    REQ_ID,
    STUS_ID  
  )
  USING INDEX PK_PEN_OBJ_REQ_D);
  
  /*
   * 요청 PEN_OBJ_M
   */
  
CREATE TABLE PEN_OBJ_M_T
(
  OBJ_TYPE_ID       VARCHAR2(100)          NOT NULL,
  OBJ_ID            VARCHAR2(300)          NOT NULL,
  APRV_ID           VARCHAR2(300) 		   NOT NULL,
  DEL_YN            CHAR(1)                NOT NULL,
  CRET_DT           TIMESTAMP(6)           NOT NULL,
  CRETR_ID          VARCHAR2(100)          NOT NULL,
  CHG_DT            TIMESTAMP(6)           NOT NULL,
  CHGR_ID           VARCHAR2(100)          NOT NULL,
  ADM_OBJ_ID        VARCHAR2(300),
  OBJ_NM            VARCHAR2(300),
  OBJ_ABBR_NM       VARCHAR2(300),
  OBJ_DESC          VARCHAR2(2000),
  PATH_OBJ_TYPE_ID  VARCHAR2(100),
  PATH_OBJ_ID       VARCHAR2(300)
);

CREATE UNIQUE INDEX PK_PEN_OBJ_M_T
ON PEN_OBJ_M_T (
    OBJ_TYPE_ID ASC,
    OBJ_ID  ASC,
	APRV_ID ASC
);

ALTER TABLE PEN_OBJ_M_T ADD (
  PRIMARY KEY
  (
    OBJ_TYPE_ID,
    OBJ_ID,
	APRV_ID
  )
  USING INDEX PK_PEN_OBJ_M_T);
  
  /*
   * 요청 PEN_OBJ_D
   */
  
CREATE TABLE PEN_OBJ_D_T
(
  OBJ_TYPE_ID  VARCHAR2(100)               NOT NULL,
  OBJ_ID       VARCHAR2(300)               NOT NULL,
  ATR_ID_SEQ   NUMBER                      NOT NULL,
  ATR_VAL_SEQ  NUMBER                      NOT NULL,
  APRV_ID      VARCHAR2(300) 			   NOT NULL,
  DEL_YN       CHAR(1)                     NOT NULL,
  CRET_DT      TIMESTAMP(6)                NOT NULL,
  CRETR_ID     VARCHAR2(100)               NOT NULL,
  CHG_DT       TIMESTAMP(6)                NOT NULL,
  CHGR_ID      VARCHAR2(100)               NOT NULL,
  OBJ_ATR_VAL  VARCHAR2(4000)
);

CREATE UNIQUE INDEX PK_PEN_OBJ_D_T
ON PEN_OBJ_D_T (
    OBJ_TYPE_ID ASC,
    OBJ_ID  ASC,
    ATR_ID_SEQ ASC,
    ATR_VAL_SEQ ASC,
	APRV_ID ASC
);

ALTER TABLE PEN_OBJ_D_T ADD (
  PRIMARY KEY
  (
    OBJ_TYPE_ID,
    OBJ_ID,
    ATR_ID_SEQ,
    ATR_VAL_SEQ,
	APRV_ID
  )
  USING INDEX PK_PEN_OBJ_D_T);
  
  /*
   * 요청 PEN_OBJ_R
   */
  
CREATE TABLE PEN_OBJ_R_T
(
  OBJ_TYPE_ID       VARCHAR2(100)          NOT NULL,
  OBJ_ID            VARCHAR2(300)          NOT NULL,
  REL_OBJ_TYPE_ID   VARCHAR2(100)          NOT NULL,
  REL_OBJ_ID        VARCHAR2(300)          NOT NULL,
  APRV_ID           VARCHAR2(300) 		   NOT NULL,
  DEL_YN            CHAR(1)                NOT NULL,
  CRET_DT           TIMESTAMP(6)                NOT NULL,
  CRETR_ID          VARCHAR2(100)          NOT NULL,
  CHG_DT            TIMESTAMP(6)                NOT NULL,
  CHGR_ID           VARCHAR2(100)          NOT NULL,
  REL_TYPE_ID       VARCHAR2(100),
  OBJ_REL_ANALS_CD  VARCHAR2(3)
);

CREATE UNIQUE INDEX PK_PEN_OBJ_R_T
ON PEN_OBJ_R_T (
    OBJ_TYPE_ID ASC,
    OBJ_ID  ASC,
    REL_OBJ_TYPE_ID ASC,
    REL_OBJ_ID ASC,
	APRV_ID ASC
);

ALTER TABLE PEN_OBJ_R_T ADD (
  PRIMARY KEY
  (
    OBJ_TYPE_ID,
    OBJ_ID,
    REL_OBJ_TYPE_ID,
    REL_OBJ_ID,
	APRV_ID
  )
  USING INDEX PK_PEN_OBJ_R_T);


CREATE TABLE PEN_APRV_M
(
    APRV_ID         VARCHAR2(300) NOT NULL,
    DEL_YN          CHAR(1) NOT NULL,
    CRET_DT         TIMESTAMP(6) NOT NULL,
    CRETR_ID        VARCHAR2(100) NOT NULL,
    CHG_DT          TIMESTAMP(6) NOT NULL,
    CHGR_ID         VARCHAR2(100) NOT NULL,
    APRV_NM         VARCHAR2(300),
    APRV_DESC       VARCHAR2(300),
    APRV_TYPE_CD    VARCHAR2(20),
    APRV_REQR_ID    VARCHAR2(100),
    APRV_REQ_DT     TIMESTAMP(6),
    LAST_LINE_ID    VARCHAR2(100),
    LAST_STUS_CD    VARCHAR2(10),
    APRV_OBJ_ID     VARCHAR2(300),
    APRV_LINK_ID    VARCHAR2(300),
    OBJ_TYPE_ID     VARCHAR2(300),
    OBJ_ID          VARCHAR2(300),
    APRV_REQR_CD    VARCHAR2(20),
    APRV_ATR01_VAL  VARCHAR2(300)
);

CREATE UNIQUE INDEX PK_PEN_APRV_M
ON PEN_APRV_M (APRV_ID);

ALTER TABLE PEN_APRV_M ADD (
	PRIMARY KEY (APRV_ID)
	USING INDEX PK_PEN_APRV_M
);

CREATE INDEX IDX_PEN_APRV_M01
ON PEN_APRV_M (APRV_TYPE_CD);

CREATE INDEX IDX_PEN_APRV_M02
ON PEN_APRV_M (OBJ_ID);


CREATE TABLE PEN_APRV_D
(
    APRV_ID             VARCHAR2(300) NOT NULL,
    APRV_DETL_ID        VARCHAR2(300) NOT NULL,
    DEL_YN              CHAR(1) NOT NULL,
    CRET_DT             TIMESTAMP(6) NOT NULL,
    CRETR_ID            VARCHAR2(100) NOT NULL,
    CHG_DT              TIMESTAMP(6) NOT NULL,
    CHGR_ID             VARCHAR2(100) NOT NULL,
    APRV_LINE_ID        VARCHAR2(100),
    APRV_PRCS_SORT_NO   NUMBER(10),
    APRV_PRCS_NM        VARCHAR2(300),
    APRV_USER_ID        VARCHAR2(100),
    APRV_DESC           VARCHAR2(300),
    REAL_APRV_USER_ID   VARCHAR2(100),
    APRV_DT             TIMESTAMP(6),
    APRV_RSLT_CD        VARCHAR2(10),
    APRV_LINE_OBJ_ID    VARCHAR2(300),
    APRV_ATR01_VAL      VARCHAR2(300),
    APRV_ATR02_VAL      VARCHAR2(300),
    APRV_ATR03_VAL      VARCHAR2(300),
    APRV_ATR04_VAL      VARCHAR2(300),
    APRV_ATR05_VAL      VARCHAR2(300),
    APRV_ATR06_VAL      VARCHAR2(300),
    APRV_ATR07_VAL      VARCHAR2(300),
    APRV_ATR08_VAL      VARCHAR2(300),
    APRV_ATR09_VAL      VARCHAR2(300),
    APRV_ATR10_VAL      VARCHAR2(300)
);

CREATE UNIQUE INDEX PK_PEN_APRV_D
ON PEN_APRV_D (APRV_ID,APRV_DETL_ID);

ALTER TABLE PEN_APRV_D ADD (
	PRIMARY KEY (APRV_ID,APRV_DETL_ID)
	USING INDEX PK_PEN_APRV_D
);

CREATE TABLE PEN_APRV_F
(
    APRV_ID         VARCHAR2(300) NOT NULL,
    APRV_DETL_ID    VARCHAR2(300) NOT NULL,
    FILE_NO         NUMBER NOT NULL,
    DEL_YN          CHAR(1) NOT NULL,
    CRET_DT         TIMESTAMP(6) NOT NULL,
    CRETR_ID        VARCHAR2(100) NOT NULL,
    CHG_DT          TIMESTAMP(6) NOT NULL,
    CHGR_ID         VARCHAR2(100) NOT NULL,
    FILE_ID         VARCHAR2(300),
    FILE_NM         VARCHAR2(300),
    FILE_SIZE       VARCHAR2(300),
    FILE_TYPE       VARCHAR2(300),
    FILE_PATH       VARCHAR2(300)
);

CREATE UNIQUE INDEX PK_PEN_APRV_F
ON PEN_APRV_F (APRV_ID,APRV_DETL_ID,FILE_NO);

ALTER TABLE PEN_APRV_F ADD (
	PRIMARY KEY (APRV_ID,APRV_DETL_ID,FILE_NO)
	USING INDEX PK_PEN_APRV_F
);
