CREATE TABLE PEN_USER_AUTH
(
   USER_ID    NVARCHAR2 (200) NOT NULL,
   DEL_YN     NCHAR (1) NOT NULL,
   CRET_DT    TIMESTAMP (6) NOT NULL,
   CRETR_ID   NVARCHAR2 (200) NOT NULL,
   CHG_DT     TIMESTAMP (6) NOT NULL,
   CHGR_ID    NVARCHAR2 (200) NOT NULL,
   AUTH_NM    NVARCHAR2 (20) NOT NULL
);


COMMENT ON COLUMN PEN_USER_AUTH.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN PEN_USER_AUTH.DEL_YN IS '삭제여부';
COMMENT ON COLUMN PEN_USER_AUTH.CRET_DT IS '생성일자';
COMMENT ON COLUMN PEN_USER_AUTH.CRETR_ID IS '생성자';
COMMENT ON COLUMN PEN_USER_AUTH.CHG_DT IS '수정일자';
COMMENT ON COLUMN PEN_USER_AUTH.CHGR_ID IS '수정자';
COMMENT ON COLUMN PEN_USER_AUTH.AUTH_NM IS '권한명';
COMMENT ON TABLE PEN_USER_AUTH IS '사용자권한정보';


CREATE TABLE PEN_USER_M
(
   USER_ID                   NVARCHAR2 (200) NOT NULL,
   DEL_YN                    NCHAR (1) NOT NULL,
   CRET_DT                   TIMESTAMP (6) NOT NULL,
   CRETR_ID                  NVARCHAR2 (200) NOT NULL,
   CHG_DT                    TIMESTAMP (6) NOT NULL,
   CHGR_ID                   NVARCHAR2 (200) NOT NULL,
   USER_NM                   NVARCHAR2 (200) NOT NULL,
   USER_PASSWORD             NVARCHAR2 (200) NOT NULL,
   TEL_NO                    NVARCHAR2 (100),
   HP_NO                     NVARCHAR2 (100),
   EMAIL_ADDR                NVARCHAR2 (200),
   ORG_ID                    NVARCHAR2 (100),
   ACCOUNT_NON_EXPIRED       NCHAR (1) NOT NULL,
   ACCOUNT_NON_LOCKED        NCHAR (1) NOT NULL,
   CREDENTIALS_NON_EXPIRED   NCHAR (1) NOT NULL,
   ACCOUNT_ENABLED           NCHAR (1) NOT NULL,
   LOGIN_FAIL_CNT            NUMBER NOT NULL,
   PASSWORD_LAST_CHG_DT      TIMESTAMP (6) NOT NULL,
   LOGIN_LAST_DT             TIMESTAMP (6)
);

CREATE UNIQUE INDEX PK_PEN_USER_M ON PEN_USER_M
(USER_ID   ASC);

ALTER TABLE PEN_USER_M
    ADD CONSTRAINT  PK_PEN_USER_M PRIMARY KEY (USER_ID);
    

COMMENT ON COLUMN PEN_USER_M.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN PEN_USER_M.DEL_YN IS '삭제여부';
COMMENT ON COLUMN PEN_USER_M.CRET_DT IS '생성일자';
COMMENT ON COLUMN PEN_USER_M.CRETR_ID IS '생성자';
COMMENT ON COLUMN PEN_USER_M.CHG_DT IS '수정일자';
COMMENT ON COLUMN PEN_USER_M.CHGR_ID IS '수정자';
COMMENT ON COLUMN PEN_USER_M.USER_NM IS '사용자명';
COMMENT ON COLUMN PEN_USER_M.USER_PASSWORD IS '사용자 패스워드';
COMMENT ON COLUMN PEN_USER_M.TEL_NO IS '전화번호';
COMMENT ON COLUMN PEN_USER_M.HP_NO IS '휴대폰번호';
COMMENT ON COLUMN PEN_USER_M.EMAIL_ADDR IS '이메일주소';
COMMENT ON COLUMN PEN_USER_M.ORG_ID IS '조직 아이디';
COMMENT ON COLUMN PEN_USER_M.ACCOUNT_NON_EXPIRED IS '계정 비 만료';
COMMENT ON COLUMN PEN_USER_M.ACCOUNT_NON_LOCKED IS '계정 비 잠금';
COMMENT ON COLUMN PEN_USER_M.CREDENTIALS_NON_EXPIRED IS '자격증명 미 만료';
COMMENT ON COLUMN PEN_USER_M.ACCOUNT_ENABLED IS '계정 활성';
COMMENT ON COLUMN PEN_USER_M.LOGIN_FAIL_CNT IS '로그인 실패 횟수';
COMMENT ON COLUMN PEN_USER_M.PASSWORD_LAST_CHG_DT IS '패스워드 최종 수정일자';
COMMENT ON COLUMN PEN_USER_M.LOGIN_LAST_DT IS '최종 로그인 일시';
COMMENT ON TABLE PEN_USER_M IS '사용자정보';

INSERT INTO PEN_USER_M
VALUES ('admin', 'N', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin', '관리자', '$2a$10$N.MNTB3swNQ5awe3uSIBweBlC2WU8A2NFUvhrzDYtbmbLv9PSBYu2', NULL, NULL, NULL, NULL, 'Y', 'Y', 'Y', 'Y', 0, CURRENT_TIMESTAMP, NULL);

COMMIT;

/* 사용자 View */
CREATE OR REPLACE VIEW V_PTL_COM_USER
AS 
SELECT 
    T101.USER_ID,
    T101.DOMAIN_ID,
    T101.GROUP_ID,
    T101.STATUS,
    T101.CREATE_DT,
    T101.MODIFY_DT,
    T101.NAME,
    T101.CODE,
    T101.LOGIN_ID,
    T101.START_DATE,
    T101.END_DATE,
    T101.EMAIL,
    T101.PHONE,
    T101.MOBILE,
    T101.EX_SEX,
    T101.EX_EMP_STATUS,
    T101.EX_EMP_DV_CD,
    T101.EX_PROVUSERTYPE,
    T101.EX_ENG_NAME,
    T101.EX_HOFC_STTS_CD,
    T101.EX_UNDK_BIZ_NM,
    T101.EX_ENTERDATE,
    T101.EX_LGT_PSTN_DV_CD,
    T101.EX_LGT_PSTN_DV_NM,
    T101.EX_DUTYCODE,
    T101.EX_DUTYNAME,
    T101.EX_DEPT_CD,
    T101.EX_DEPT_NAME,
    T101.EX_DEPT_LEVEL,
    T101.EX_COMP_NAME,
    T101.EX_SITECHARGER,
    T101.EX_SITECHARGERINFO,
    T101.EX_OUTER_EMAIL,
    T101.EX_MAC_ADDR,
    T101.EX_OLD_CODE,
    'M' AS USER_GBN, /* 마당유저 */
    NULL AS USER_PW
FROM PTL_COM_USER T101
UNION ALL
SELECT 
    T101.USER_ID,
    NULL AS DOMAIN_ID,
    T101.ORG_ID AS GROUP_ID,
    T101.DEL_YN AS STATUS,
    T101.CRET_DT AS CREATE_DT,
    T101.CHG_DT AS MODIFY_DT,
    T101.USER_NM AS NAME,
    T101.USER_ID AS CODE,
    T101.USER_ID AS LOGIN_ID,
    NULL AS START_DATE,
    NULL AS END_DATE,
    T101.MAIL_ID AS EMAIL,
    T101.HP_TEL_NO AS PHONE,
    NULL AS MOBILE,
    NULL AS EX_SEX,
    NULL AS EX_EMP_STATUS,
    NULL AS EX_EMP_DV_CD,
    NULL AS EX_PROVUSERTYPE,
    NULL AS EX_ENG_NAME,
    NULL AS EX_HOFC_STTS_CD,
    NULL AS EX_UNDK_BIZ_NM,
    NULL AS EX_ENTERDATE,
    NULL AS EX_LGT_PSTN_DV_CD,
    NULL AS EX_LGT_PSTN_DV_NM,
    NULL AS EX_DUTYCODE,
    NULL AS EX_DUTYNAME,
    NULL AS EX_DEPT_CD,
    NULL AS EX_DEPT_NAME,
    NULL AS EX_DEPT_LEVEL,
    NULL AS EX_COMP_NAME,
    NULL AS EX_SITECHARGER,
    NULL AS EX_SITECHARGERINFO,
    NULL AS EX_OUTER_EMAIL,
    NULL AS EX_MAC_ADDR,
    NULL AS EX_OLD_CODE,
    'P' AS USER_GBN, /* 마당유저 */
    T101.USER_PW AS USER_PW
FROM PEN_USER_M T101
WHERE NOT EXISTS (SELECT 1 FROM PTL_COM_USER T102 WHERE T101.USER_ID = T102.USER_ID);